# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\formDetalhesArtigo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(413, 288)
        self.label_id = QtWidgets.QLabel(Form)
        self.label_id.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_id.setObjectName("label_id")
        self.lineEdit_preco = QtWidgets.QLineEdit(Form)
        self.lineEdit_preco.setGeometry(QtCore.QRect(100, 140, 71, 20))
        self.lineEdit_preco.setObjectName("lineEdit_preco")
        self.comboBox_categoria = QtWidgets.QComboBox(Form)
        self.comboBox_categoria.setGeometry(QtCore.QRect(100, 200, 211, 22))
        self.comboBox_categoria.setObjectName("comboBox_categoria")
        self.label_titulo = QtWidgets.QLabel(Form)
        self.label_titulo.setGeometry(QtCore.QRect(70, 10, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(20)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.label_preco = QtWidgets.QLabel(Form)
        self.label_preco.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.label_preco.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_preco.setObjectName("label_preco")
        self.label_stock = QtWidgets.QLabel(Form)
        self.label_stock.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_stock.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_stock.setObjectName("label_stock")
        self.pushButton_voltar = QtWidgets.QPushButton(Form)
        self.pushButton_voltar.setGeometry(QtCore.QRect(330, 230, 61, 23))
        self.pushButton_voltar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Interfaces/imagens/voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_voltar.setIcon(icon)
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.lineEdit_designacao = QtWidgets.QLineEdit(Form)
        self.lineEdit_designacao.setGeometry(QtCore.QRect(100, 110, 281, 20))
        self.lineEdit_designacao.setObjectName("lineEdit_designacao")
        self.lineEdit_id = QtWidgets.QLineEdit(Form)
        self.lineEdit_id.setGeometry(QtCore.QRect(100, 80, 51, 20))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_categoria = QtWidgets.QLabel(Form)
        self.label_categoria.setGeometry(QtCore.QRect(10, 200, 81, 16))
        self.label_categoria.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_categoria.setObjectName("label_categoria")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\Interfaces/imagens/produtos.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_designacao = QtWidgets.QLabel(Form)
        self.label_designacao.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label_designacao.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_designacao.setObjectName("label_designacao")
        self.lineEdit_stock = QtWidgets.QLineEdit(Form)
        self.lineEdit_stock.setGeometry(QtCore.QRect(100, 170, 71, 20))
        self.lineEdit_stock.setObjectName("lineEdit_stock")
        self.label_moeda = QtWidgets.QLabel(Form)
        self.label_moeda.setGeometry(QtCore.QRect(180, 140, 81, 16))
        self.label_moeda.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_moeda.setObjectName("label_moeda")
        self.pushButton_gravar = QtWidgets.QPushButton(Form)
        self.pushButton_gravar.setGeometry(QtCore.QRect(250, 230, 71, 23))
        self.pushButton_gravar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Interfaces/imagens/guardar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_gravar.setIcon(icon1)
        self.pushButton_gravar.setObjectName("pushButton_gravar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Detalhes Artigo"))
        self.label_id.setText(_translate("Form", "Id. Artigo:"))
        self.label_titulo.setText(_translate("Form", "NOVO/ALTERAR ARTIGO"))
        self.label_preco.setText(_translate("Form", "Preço:"))
        self.label_stock.setText(_translate("Form", "Stock:"))
        self.pushButton_voltar.setText(_translate("Form", "Voltar"))
        self.label_categoria.setText(_translate("Form", "Categoria:"))
        self.label_designacao.setText(_translate("Form", "Designação:"))
        self.label_moeda.setText(_translate("Form", "€"))
        self.pushButton_gravar.setText(_translate("Form", "Gravar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
