# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\formPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 559)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 620, 90))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_encomendas = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_encomendas.setGeometry(QtCore.QRect(390, 230, 210, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_encomendas.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\imagens/encomendas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_encomendas.setIcon(icon)
        self.pushButton_encomendas.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_encomendas.setObjectName("pushButton_encomendas")
        self.pushButton_sair = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sair.setGeometry(QtCore.QRect(540, 380, 101, 91))
        self.pushButton_sair.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../../../../../Downloads/interfaces/Imagens/sair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sair.setIcon(icon1)
        self.pushButton_sair.setIconSize(QtCore.QSize(52, 52))
        self.pushButton_sair.setFlat(True)
        self.pushButton_sair.setObjectName("pushButton_sair")
        self.pushButton_categorias = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_categorias.setGeometry(QtCore.QRect(160, 150, 210, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_categorias.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\imagens/categorias.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_categorias.setIcon(icon2)
        self.pushButton_categorias.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_categorias.setObjectName("pushButton_categorias")
        self.pushButton_clientes = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clientes.setGeometry(QtCore.QRect(160, 230, 210, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_clientes.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\imagens/cliente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clientes.setIcon(icon3)
        self.pushButton_clientes.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_clientes.setObjectName("pushButton_clientes")
        self.pushButton_produtos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_produtos.setGeometry(QtCore.QRect(390, 150, 210, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_produtos.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\imagens/produtos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_produtos.setIcon(icon4)
        self.pushButton_produtos.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_produtos.setObjectName("pushButton_produtos")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Gestão de encomendas"))
        self.pushButton_encomendas.setText(_translate("MainWindow", "Encomendas"))
        self.pushButton_categorias.setText(_translate("MainWindow", "Categorias"))
        self.pushButton_clientes.setText(_translate("MainWindow", "Clientes"))
        self.pushButton_produtos.setText(_translate("MainWindow", "Artigos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
