# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\formDetalhesCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 327)
        self.label_nif = QtWidgets.QLabel(Form)
        self.label_nif.setGeometry(QtCore.QRect(20, 250, 81, 16))
        self.label_nif.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nif.setObjectName("label_nif")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\Imagens/cliente.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit_telefone = QtWidgets.QLineEdit(Form)
        self.lineEdit_telefone.setGeometry(QtCore.QRect(110, 190, 121, 20))
        self.lineEdit_telefone.setObjectName("lineEdit_telefone")
        self.lineEdit_nome = QtWidgets.QLineEdit(Form)
        self.lineEdit_nome.setGeometry(QtCore.QRect(110, 110, 281, 20))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.pushButton_gravar = QtWidgets.QPushButton(Form)
        self.pushButton_gravar.setGeometry(QtCore.QRect(260, 280, 71, 23))
        self.pushButton_gravar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Imagens/guardar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_gravar.setIcon(icon)
        self.pushButton_gravar.setObjectName("pushButton_gravar")
        self.label_morada = QtWidgets.QLabel(Form)
        self.label_morada.setGeometry(QtCore.QRect(20, 140, 81, 16))
        self.label_morada.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_morada.setObjectName("label_morada")
        self.plainTextEdit_morada = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_morada.setGeometry(QtCore.QRect(110, 140, 281, 41))
        self.plainTextEdit_morada.setObjectName("plainTextEdit_morada")
        self.pushButton_voltar = QtWidgets.QPushButton(Form)
        self.pushButton_voltar.setGeometry(QtCore.QRect(340, 280, 61, 23))
        self.pushButton_voltar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Imagens/voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_voltar.setIcon(icon1)
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.label_titulo = QtWidgets.QLabel(Form)
        self.label_titulo.setGeometry(QtCore.QRect(80, 10, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(20)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(110, 220, 281, 20))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_id = QtWidgets.QLineEdit(Form)
        self.lineEdit_id.setGeometry(QtCore.QRect(110, 80, 51, 20))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_id = QtWidgets.QLabel(Form)
        self.label_id.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_id.setObjectName("label_id")
        self.label_email = QtWidgets.QLabel(Form)
        self.label_email.setGeometry(QtCore.QRect(20, 220, 81, 16))
        self.label_email.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_email.setObjectName("label_email")
        self.label_nome = QtWidgets.QLabel(Form)
        self.label_nome.setGeometry(QtCore.QRect(20, 110, 81, 16))
        self.label_nome.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nome.setObjectName("label_nome")
        self.label_telefone = QtWidgets.QLabel(Form)
        self.label_telefone.setGeometry(QtCore.QRect(20, 190, 81, 16))
        self.label_telefone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_telefone.setObjectName("label_telefone")
        self.lineEdit_nif = QtWidgets.QLineEdit(Form)
        self.lineEdit_nif.setGeometry(QtCore.QRect(110, 250, 121, 20))
        self.lineEdit_nif.setObjectName("lineEdit_nif")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Detalhes Cliente"))
        self.label_nif.setText(_translate("Form", "NIF:"))
        self.pushButton_gravar.setText(_translate("Form", "Gravar"))
        self.label_morada.setText(_translate("Form", "Morada:"))
        self.pushButton_voltar.setText(_translate("Form", "Voltar"))
        self.label_titulo.setText(_translate("Form", "NOVO/ALTERAR CLIENTE"))
        self.label_id.setText(_translate("Form", "Id. Cliente:"))
        self.label_email.setText(_translate("Form", "Email:"))
        self.label_nome.setText(_translate("Form", "Nome:"))
        self.label_telefone.setText(_translate("Form", "Telefone:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
