# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\formCategorias.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_limpar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_limpar.setGeometry(QtCore.QRect(570, 160, 101, 21))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Interfaces/imagens/limpar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_limpar.setIcon(icon)
        self.pushButton_limpar.setFlat(True)
        self.pushButton_limpar.setObjectName("pushButton_limpar")
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltar.setGeometry(QtCore.QRect(560, 450, 101, 21))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Interfaces/imagens/voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_voltar.setIcon(icon1)
        self.pushButton_voltar.setFlat(True)
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 160, 370, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eliminar.setGeometry(QtCore.QRect(470, 450, 101, 21))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\Interfaces/imagens/excluir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_eliminar.setIcon(icon2)
        self.pushButton_eliminar.setFlat(True)
        self.pushButton_eliminar.setObjectName("pushButton_eliminar")
        self.pushButton_editar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editar.setGeometry(QtCore.QRect(380, 450, 101, 21))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\Interfaces/imagens/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_editar.setIcon(icon3)
        self.pushButton_editar.setFlat(True)
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 80, 260, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_filtrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_filtrar.setGeometry(QtCore.QRect(480, 160, 101, 21))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\Interfaces/imagens/filtrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_filtrar.setIcon(icon4)
        self.pushButton_filtrar.setFlat(True)
        self.pushButton_filtrar.setObjectName("pushButton_filtrar")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(110, 200, 551, 240))
        self.tableView.setObjectName("tableView")
        self.pushButton_novo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_novo.setGeometry(QtCore.QRect(290, 450, 101, 21))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\Interfaces/imagens/novo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_novo.setIcon(icon5)
        self.pushButton_novo.setFlat(True)
        self.pushButton_novo.setObjectName("pushButton_novo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 90, 50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\Interfaces/imagens/categorias.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_limpar.setText(_translate("MainWindow", "Limpar"))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))
        self.pushButton_eliminar.setText(_translate("MainWindow", "Eliminar"))
        self.pushButton_editar.setText(_translate("MainWindow", "Editar"))
        self.label.setText(_translate("MainWindow", "Categorias"))
        self.pushButton_filtrar.setText(_translate("MainWindow", "Filtrar"))
        self.pushButton_novo.setText(_translate("MainWindow", "Novo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
