# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\formAlterarCategoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(363, 185)
        self.pushButton_voltar = QtWidgets.QPushButton(Form)
        self.pushButton_voltar.setGeometry(QtCore.QRect(280, 140, 61, 23))
        self.pushButton_voltar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Imagens/voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_voltar.setIcon(icon)
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.lineEdit_id = QtWidgets.QLineEdit(Form)
        self.lineEdit_id.setGeometry(QtCore.QRect(100, 80, 51, 20))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_designacao = QtWidgets.QLabel(Form)
        self.label_designacao.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label_designacao.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_designacao.setObjectName("label_designacao")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\Imagens/categorias.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_titulo = QtWidgets.QLabel(Form)
        self.label_titulo.setGeometry(QtCore.QRect(70, 10, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(20)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.label_id = QtWidgets.QLabel(Form)
        self.label_id.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_id.setObjectName("label_id")
        self.lineEdit_designacao = QtWidgets.QLineEdit(Form)
        self.lineEdit_designacao.setGeometry(QtCore.QRect(100, 110, 231, 20))
        self.lineEdit_designacao.setObjectName("lineEdit_designacao")
        self.pushButton_gravar = QtWidgets.QPushButton(Form)
        self.pushButton_gravar.setGeometry(QtCore.QRect(200, 140, 71, 23))
        self.pushButton_gravar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Imagens/guardar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_gravar.setIcon(icon1)
        self.pushButton_gravar.setObjectName("pushButton_gravar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Detalhes Categoria"))
        self.pushButton_voltar.setText(_translate("Form", "Voltar"))
        self.label_designacao.setText(_translate("Form", "Designação:"))
        self.label_titulo.setText(_translate("Form", "ALTERAR CATEGORIA"))
        self.label_id.setText(_translate("Form", "Id. Categoria:"))
        self.pushButton_gravar.setText(_translate("Form", "Gravar"))
